# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-out=tfplan'
    backendServiceArm: 'MCT Tenant'
    backendAzureRmResourceGroupName: 'rg_management'
    backendAzureRmStorageAccountName: 'tfdevopsmct'
    backendAzureRmContainerName: 'tfdevopscnt'
    backendAzureRmKey: 'tf/terraform.tfstate'
