name: $(moduleName)-$(moduleVersion)

variables:
- template: VirtualNetwork.pipeline.environments.yaml
- template: VirtualNetwork.pipeline.variables.yml
- template: /Modules-Terraform/.global/global.variables.yml

trigger:
  branches:
    include:
      - develop
      - master
  paths:
    include:
      - Modules-Terraform/VirtualNetwork/2.0

stages:

- stage: Validate
  jobs:
  - template: VirtualNetwork.pipeline.validate.yml

- stage: plan
  jobs:
  - template: VirtualNetwork.pipeline.plan.yml

- stage: apply
  jobs:
  - template: VirtualNetwork.pipeline.apply.yml