variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    environment: dev
    secretsFilter: 'KeyVault--Name--$(akv)'    
    resource_group_name_vnet: rg-hub-zan-003
    dns_service_ip: ''
    resource_name_vnet: 'vnet-spoke-zan-001'
    address_space: '["10.10.0.0/16"]'
    subnet_prefixes: '["10.10.1.0/24", "10.10.2.0/24", "10.10.3.0/26","10.10.4.0/27"]'
    subnet_names: '["snet-sqmi-zan-001", "snet-shared-zan-001", "AzureFirewallSubnet", "gatewaysubnet"]'
    #overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--<ResourceNameHere>" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: akv-jagga-zan-0002

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    environment: sit
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>,StorageAccount--ResourceId--<ResourceNameHere>'    
    resourceGroup_net: RG-SIT-NET
    connectionService: azure-spn
    overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--<ResourceNameHere>" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: sit-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
    environment: uat
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>,StorageAccount--ResourceId--<ResourceNameHere>'    
    resourceGroup_net: RG-UAT-NET
    connectionService: azure-spn
    overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--<ResourceNameHere>" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: uat-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    environment: prd
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>,StorageAccount--ResourceId--<ResourceNameHere>'    
    resourceGroup_net: RG-PRD-NET
    connectionService: azure-spn
    overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--<ResourceNameHere>" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: prd-akv-001